### ISSUE TITLE
Please upgrade/remove old dependencies with vulnerabilities

### ISSUE THREAD

**Issue by trygveaa** [kgryte/utils-is-little-endian#1]
The version of `update-notifier` that this package depends on transitively depends on an old version of `dot-prop` with a vulnerability: https://www.npmjs.com/advisories/1213

Can you please upgrade `update-notifier` to the latest version, or preferably remove the `update-notifier` dependency? Since this package hasn't had a release in 6 years, I think it's safe to say that including `update-notifier` isn't very useful, and removing it would prevent this from happening again.

**Comment by kgryte** [comment]
@trygveaa Thanks for the ping. I recommend switching to this package: https://github.com/stdlib-js/assert-is-little-endian. The linked package supersedes this package and does not depend on `update-notifier`.
